### PR TITLE
Move to modular lodash

### PR DESCRIPTION
**Pull request by mwaldstein**
* Removed use of `chain` as it required (effectively) all of lodash
 * Switched to native Function.bind for the same reason.

With similar change to graphlib, https://github.com/dagrejs/graphlib/pull/86 

 * dagre.js: 636K => 317K
 * dagre.min.js: 554K => 278K

### CODE REVIEW

**Comment by mwaldstein** [comment]
Some notes -

This is more invasive than changes to graphlib or dagre-d3. The reason is that 2 lodash functions effectively ended up pulling in or needing all of lodash, negating the exercise. These functions were used in limited places, so they were written out. 

## _.chain
Permits composing functions rather than nesting - e.g.
```
var result = ._chain(input).function1().function2().value()
```
vs
```
var result = function2(function1(input))
```
used in lib/order/cross-count.js and lib/order/resolve-conflicts.js

In both cases there were only 2 functions in the chain, so while nesting is less attractive, it is not illegible.

No risk.

## _.bind
The lodash bind is fairly powerful with a lot of options. dagre only uses it to set a scope for 'this' in lib/position/bk.js

There is a low risk with this change. lodash uses `Function.prototype.apply` to create its bind which has been supported in browsers [forever](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#Browser_compatibility). I made the change to use the native `Function.prototype.bind` which does not go back as far - mainly not supported by ie8 ([compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Browser_compatibility))

There are options to add a polyfill if ie8 support is desired.

**Comment by mwaldstein** [comment]
Follow-up - graphlib is already using `Function.prototype.bind`, so ie8 is already non-functional.

**Comment by lutzroeder** [comment]
The `dagre.js` built via `mwaldstein:master` seems to be larger than `dagre:master`. Any ideas?

**Comment by mwaldstein** [comment]
I would imagine it is because of using the unmodified graphlib.

Without also making this change https://github.com/dagrejs/graphlib/pull/86, you end up still with the full lodash since graphlib gets fully bundled in.

**Pull request merged**
