### PR TITLE
Add `customOrder` and `disableOptimalOrderHeuristic`

### PR DESCRIPTION
**Pull request by futpib**
This allows users to customize ordering algorithm. May help address #189, #201 and other

### CODE REVIEW

**Comment by FelixSchwarzmeier** [comment]
@lutzroeder could this PR please be merged for the next release? Being able to customize the order is a highly requested feature for my project.

**Comment by dlangerenken** [comment]
@lutzroeder any updates?

**Comment by JoshuaeKaiser** [comment]
Same here, quite an important update.

**Comment by apdsm** [comment]
Would love if this could get merged!

**Comment by Rishav159** [comment]
@lutzroeder Any update on this? This is an important feature for my project.

**Comment by TEJATJ** [comment]
Yes this is a good and a needed feature. For dynamic graph-building/flow-creations an option like this would help minimise the frequent ordering of nodes.

**Comment by rustedgrail** [comment]
I'll take a look at the branch soon, but at a cursory glance, it looks fine.

**Comment by rustedgrail** [comment]
Thank you for your help and for our patience

**Comment by judehunter** [comment]
Hi, this looks great. Could we get some guidance on how to use this to achieve some common use cases, please? @rustedgrail @futpib

**Comment by dongtc** [comment]
Have a doubt，seems it doesn't merged into master ? https://github.com/dagrejs/dagre/blob/master/lib/layout.js#L29

**Comment by aikrez** [comment]
> Have a doubt，seems it doesn't merged into master ? https://github.com/dagrejs/dagre/blob/master/lib/layout.js#L29

It is available https://github.com/dagrejs/dagre/blob/master/lib/order/index.js#L41

**Comment by TimotijevicVladimir** [comment]
This library solve the problem with dagre ordering:
@hassanmojab/dagre

Link to it:
https://www.npmjs.com/package/@hassanmojab/dagre?activeTab=readme

**Pull request merged**
